//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statistici
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemperaturaPoianaBrasov
    {
        public int t_id { get; set; }
        public Nullable<System.DateTime> data_masurare { get; set; }
        public Nullable<int> minim { get; set; }
        public Nullable<int> maxim { get; set; }
    }
}
