//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Statistici
{
    using System;
    using System.Collections.Generic;
    
    public partial class Validari
    {
        public string Titlu_calatorie { get; set; }
        public string Tip_Abonament { get; set; }
        public string Auto { get; set; }
        public string Data_validarii { get; set; }
        public string Ziua { get; set; }
        public string Nr_inmatriculare { get; set; }
        public string Ora { get; set; }
        public int v_id { get; set; }
    }
}
